name: Build Image

on:
  push:
    tags:
      - v*

jobs:
  build-poetry:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        version: [313, 312, 311, 310, 39] # python-versions
        platform: [Bookworm, Bullseye, Buster] # debian-versions
        flavor: [Poetry, Playwright]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 0
      - name: Setup JDK 17
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DEBIAN_VERSION: ${{ matrix.debian }}
          FLAVOR: ${{ matrix.flavor }}
          PUBLISHING_DOCKER_USERNAME: ${{ secrets.PUBLISHING_DOCKER_USERNAME }}
          PUBLISHING_DOCKER_PASSWORD: ${{ secrets.PUBLISHING_DOCKER_PASSWORD }}
          PUBLISHING_DOCKER_TOKEN: ${{ secrets.PUBLISHING_DOCKER_TOKEN }}
        run: |
          ./scripts/ci_build.sh

  release:
    runs-on: ubuntu-20.04
    needs: [build-poetry]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 0
      - name: Setup JDK 17
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        env:
          PUBLISHING_GITHUB_TOKEN: ${{ secrets.PUBLISHING_GITHUB_TOKEN }}
        run: |
          ./gradlew githubRelease
