name: Build Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup JDK 17
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        env:
          PUBLISHING_GITHUB_TOKEN: ${{ secrets.PUBLISHING_GITHUB_TOKEN }}
        run: |
          ./gradlew githubRelease
